package utils


enum class LibyanCities(val arabicName: String) {
    TRIPOLI("طرابلس"),
    BENGHAZI("بنغازي"),
    MISRATA("مصراتة"),
    AlZWZIYA("الزاوية"),
    ZLITEN("زليتن"),
    BAYDA("البيضاء"),
    AJDABIYA("اجدابيا"),
    GARYAN("غريان"),
    TOBRUK("طبرق"),
    SABRATA("صبراتة"),
    SABHA("سبها"),
    KHOMS("الخمس"),
    DERNA("درنة"),
    SIRTE("سرت"),
    JAMIL("الجميل"),
    KUFRA("الكفرة"),
    MARJ("المرج"),
    YEFREN("يفرن"),
    TARHUNA("ترهونة"),
    MSLATA("مسلاتة"),
    BANI_WALID("بني وليد"),
    SIRMAN("صرمان"),
    RIKDALIN("رقدالين"),
    ZINTAN("الزنتان"),
    ZUWARA("زوارة"),
    SHAQIQA("الشقيقة"),
    SHAHAT("شحات"),
    UBARI("أوباري"),
    ABIAR("الأبيار"),
    ZALTAN("زلطن"),
    QUBA("القبة"),
    TAOURGHA("تاورغاء"),
    MAYA("الماية"),
    MURZUQ("مرزق"),
    BREGA("البريقة"),
    HUN("هون"),
    JALO("جالو"),
    NALUT("نالوت"),
    SULUQ("سلوق"),
    MIZDA("مزدة"),
    RAS_LANUF("راس لانوف"),
    ARABAN("العربان"),
    WADDAN("ودان"),
    AJEELAT("العجيلات"),
    TOKRA("توكرة"),
    BRAK("براك"),
    GHADAMES("غدامس"),
    GHAT("غات"),
    AWJLA("أوجلة"),
    WUSTA_SHAQIQA("الوسطى الشقيقة"),
    SOUSA("سوسة"),
    RABIANA("ربيانة"),
    FASANU("فسانو"),
    FAISAL("فيصل"),
    TADAMUN("التضامن"),
    AWAINIA_MASHASHIA("العوينية المشاشية"),
    ZAWIYA_BAQUL("زاوية الباقول"),
    ABUQILA_MASHASHIA("أبوقيلةالمشاشية"),
    WAMS("وامس"),
    HAI_MASHASHIA("حي المشاشية"),
    AIN_MASHASHIA("عين المشاشية"),
    TAJURA("تاجوراء");
}