package utils


enum class LibyanCities(val arabicName: String) {
    WesternRegion("المنطقة الغربية"),
    CentralRegion("المنطقة الوسطى"),
    EasternProvince("المنطقة الشرقية"),
    Southernarea("المنطقة الجنوبية"),
    westernmountain("الجبل الغربي"),
    TRIPOLI("طرابلس"),
    BENGHAZI("بنغازي"),
    MISRATA("مصراتة"),
    SIRTE("سرت"),
    TAJURA("تاجوراء"),
    Garabulli("القره بوللي"),
    Cucumberpalace("قصر الخيار"),
    MSLATA("مسلاتة"),
    KHOMS("الخمس"),
    ZLITEN("زليتن"),
    AlZWZIYA("الزاوية"),
    MAYA("الماية"),
    SIRMAN("صرمان"),
    AJEELAT("العجيلات"),
    SABRATA("صبراتة"),
    JAMIL("الجميل"),
    RIKDALIN("رقدالين"),
    ZUWARA("زوارة"),
    ZALTAN("زلطن"),
    BAYDA("البيضاء"),
    AJDABIYA("اجدابيا"),
    TOBRUK("طبرق"),
    DERNA("درنة"),
    MARJ("المرج"),
    MURZUQ("مرزق"),
    BREGA("البريقة"),
    GARYAN("غريان"),
    SABHA("سبها"),
    KUFRA("الكفرة"),
    YEFREN("يفرن"),
    TARHUNA("ترهونة"),
    BANI_WALID("بني وليد"),
    ZINTAN("الزنتان"),
    SHAQIQA("الشقيقة"),
    SHAHAT("شحات"),
    UBARI("أوباري"),
    ABIAR("الأبيار"),
    QUBA("القبة"),
    TAOURGHA("تاورغاء"),
    HUN("هون"),
    JALO("جالو"),
    NALUT("نالوت"),
    SULUQ("سلوق"),
    MIZDA("مزدة"),
    RAS_LANUF("راس لانوف"),
    ARABAN("العربان"),
    WADDAN("ودان"),
    TOKRA("توكرة"),
    BRAK("براك"),
    GHADAMES("غدامس"),
    GHAT("غات"),
    AWJLA("أوجلة"),
    WUSTA_SHAQIQA("الوسطى الشقيقة"),
    SOUSA("سوسة"),
    RABIANA("ربيانة"),
    FASANU("فسانو"),
    FAISAL("فيصل"),
    TADAMUN("التضامن"),
    AWAINIA_MASHASHIA("العوينية المشاشية"),
    ZAWIYA_BAQUL("زاوية الباقول"),
    ABUQILA_MASHASHIA("أبوقيلةالمشاشية"),
    WAMS("وامس"),
    HAI_MASHASHIA("حي المشاشية"),
    AIN_MASHASHIA("عين المشاشية"),
}